### ISSUE TITLE
[Feature] Add a link and dummy page as ROI Rankign page

### ISSUE THREAD

**Issue by chm1975** [protofire/livepeer-alerts-frontend#112]
###Goal:
-   Explore and analyze the interest of delegators and orchestrators (delegates)  on the ROI Ranking information.
- The goal is to build a dummy page in order to measure the access and evaluate how we continue with this ROI Ranking part.
- We have to check the way to make the ROI Table interesting for Transcoders (delegate - orchestrators)
- We need to follow up the clicks done on the ROI Ranking link and measure this with Analytics

###ToDo:
- Design on the home page the best place to put a link to the dummy page.
- Design dummy page including:
 -  a text "Comming soon"
 - ROI Table: acomodar la info para que parezca intersante y verdadera, pero anonimizar o poner las address como borrosas. La tabla tiene que llamar la atencion por su info importante y a la vez sugerir que es info de ejemplo.
 - add a link ‘talk to us’ that carry out to our livepeer telegram channel: t.me/livepeertools

###Resources:
- Current home design page: https://livepeer-alerts-frontend-stag.herokuapp.com/
- Last ROI Ranking design page: https://app.zeplin.io/project/5b71fb9cd86c791b1612c035/screen/5d2dcd881a8d2a4c0a7496bd

**Comment by chm1975** [comment]
Feedbak and TODO:
 ☐ List de 25 active transcoders
  ☐ Make all active icons in green
  ☐ remove the link from the blurred address. Just set the "on mouse over" action that show subline
  ☐ Every address must be difference
  ☐ Remove pagination or navigation from table. Just show "25 active transcoders"
  ☐ All values have to be differents. 
       Make an execel file. Copy the 25 active transcoders with address, total stake, reward cut, missed rewards calls (efficiency) and active rounds. Add manually the calculated columns: Roi per 100 LPT and Trend (this las just put 70% green and 30% red.)
  ☐ These are the columns and the order to show (remove last round, ROI (ETH)):
     #, Transcoder, Total Stake, Reward Cut,  Efficiency, Active Rounds, ROI per 1000 LPT, Trend
  ☐ Add a Title to the column name:
        ☐ Effciency: "Percentage of successful Reward Calls"
        ☐ Trend: "Rewards trend of 30 days."

**Comment by mariano-aguero** [comment]
All items are done, I will close this issue
