### ISSUE TITLE
Fix page not found on Netlify with react router

### ISSUE THREAD

**Issue by mariano-aguero** [protofire/livepeer-alerts-frontend#35]
See error
![screenshot_20190117_090904](https://user-images.githubusercontent.com/1144028/51317930-a6794680-1a37-11e9-9d4e-b5c9e1ef6b8c.png)

**Comment by ridbay** [comment]
Create a file called “_redirects” inside your public folder, then add  `/*    /index.html   200` to the “_redirects” file and deploy.

**Comment by ghost** [comment]
how do i create a _redirects file

**Comment by iamchandankrishna** [comment]
> Create a file called “_redirects” inside your public folder, then add `/* /index.html 200` to the “_redirects” file and deploy.

can you send me the file
